---
- name: install some package in all nodes
  hosts: all
  become: true
  tasks:

  - name: stop  git in all nodes
    yum:
      name: httpd
      state: installed
    notify: start service in all nodes

  handlers:    
  - name: start service in all nodes
    service:
      name: httpd
      state: started

