---
- name: install some package in all nodes
  hosts: all
  become: yes
  tasks:
  - name: install git in all nodes
    yum:
      name: httpd
      state: present

  - name: install git in all nodes
    service:
      name: httpd
      state: stoped


