---
- name: install some package in all nodes
  hosts: all
  become: true
  tasks:

  - name: install git in all nodes
    yum:
      name: httpd
      state: installed
    
  - name: start service in all nodes
    service:
      name: httpd
      state: started
