---
- name: this palybook createthe users
  hosts: all
  become: yes
  tasks:

  - name: install java on DEBAIN
    yum:
     name: java
     state: present
    when: ansible_os_family == "RedHat"

  - name: install java on DEBAIN
    apt:
     name: java
     state: present
    when: ansible_os_family == "Debain"

  - name: Download tomcat
    get_url:
     url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.93/bin/apache-tomcat-8.5.93.tar.gz
     dest: /opt

  - name: extract tomcat
    unarchive:
     src: /opt/apache-tomcat-8.5.93.tar.gz
     dest: /opt
     remote_src: yes

  - name: give execute permision
    file:
     path: /opt/apache-tomcat-8.5.93/bin/startup.sh
     mode: '0777'

  - name: starting tomcat
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.93/bin
 
