---
- name: this palybook createthe users
  hosts: all
  become: yes
  tasks: 
  - name: create users
    user: name='{{item}}' state=present
    with_items:
        - shakar
        - shiva
        - nalina

